<?php

namespace OmniPorter\Traits;

use OmniPorter\Import\Imports\GenericImport;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Maatwebsite\Excel\Facades\Excel;

trait HasImport
{
    public static function import(string $filePath, bool $update, ?string $notifiableEmail = null, ?string $associationMethod = null, ?int $chunkSize = null): void
    {
        $batchId = Str::uuid()->toString();
        $chunkSize = $chunkSize ?? static::getImportChunkSize();
        $associationMethod = $associationMethod ?? static::getImportAssociationMethod();

        Excel::queueImport(
            new GenericImport(static::class, $update, $associationMethod, $notifiableEmail, $batchId, $filePath, $chunkSize),
            $filePath,
            config('omniporter.import.disk')
        );
    }

    public static function getImportChunkSize(): int
    {
        return config('omniporter.import.chunk_size', 500);
    }

    public static function getImportAssociationMethod(): string
    {
        return 'sync';
    }

    /**
     * Hook: Runs immediately before validation during the import process.
     *
     * This method allows the model to modify the raw mapped data before it's passed
     * to the validator. Useful for pre-filling fields that are required but
     * typically generated by model hooks (e.g., work_email).
     *
     * @param array<string, mixed> $data The mapped row data (passed by reference).
     * @return void
     */
    public function beforeImportValidation(array &$data): void {}

    /**
     * Allows the model to apply import-specific context to itself before saving.
     *
     * This method is useful for setting default values (like `finalized_by`, `organization_id`,
     * `source`, `created_by`, etc.) using data provided by the importer.
     *
     * ---
     * ### Usage:
     * This method is optional, but recommended for any model needing context-aware
     * import behavior. It should mutate the model instance directly.
     *---
     * Example in a model:
     * ```
     * public function applyImportContext(array $context): void
     * {
     *     $this->finalized_by = $context['user_id'] ?? null;
     *     $this->finalized_at = now();
     * }
     * ```
     * ---
     * @param array<string, mixed> $context An associative array of contextual import data.
     *                                      Example: ```['notifiable_email' => 'user@example.com', 'source' => 'excel', 'batch_id' => 'batch_1234']```
     * @return void
     */
    public function applyImportContext(array $context): void {}

    /**
     * Returns the field(s) that uniquely identify a record during import updates.
     *
     * ---
     * The importer uses this method to determine which column(s) to use when matching existing records in the database for **update operations**.
     *
     * ---
     * ### Example (Single Unique Key)
     * ```
     * public static function getUniqueKeysForUpdate(): array|string
     * {
     *     return 'work_email';
     * }
     * ```
     *
     * ---
     * ### Example (Multiple Unique Keys)
     * ```
     * public static function getUniqueKeysForUpdate(): array|string
     * {
     *     return ['user_id', 'month', 'year'];
     * }
     * ```
     *
     * ---
     * ### When to use:
     * - **Single key**: If the table uses a primary key (e.g., `id`) or unique key (e.g., `work_email`) for uniqueness.
     * - **Multiple keys**: If the table enforces a **composite unique constraint**
     *   (e.g., `user_id`, `month', `year` in a payroll table).
     * ---
     * ### Related methods:
     * - `getUniqueKeyForImportExport()` – Defines uniqueness for import/export **relations**.
     * - `getUniqueKeysForUpdate()` – Defines uniqueness for **updates**.
     *
     * ---
     * @return array<string>|string
     *         - A string for single-column uniqueness (e.g., 'id').
     *         - An array for multi-column uniqueness (e.g., ['user_id', 'month', 'year']).
     */
    public static function getUniqueKeysForUpdate(): array|string {
        $instance = new static;
        if (property_exists($instance, 'omni_porter_config') && isset($instance->omni_porter_config['unique_key'])) {
            return $instance->omni_porter_config['unique_key'];
        }

        return static::getUniqueKeyForImportExport();
    }

    /**
     * The column name used to detect duplicate rows and drive update logic.
     *
     * For example: `'email'`, `'employee_code'`, `'sku'`
     */
    public static function getUniqueKeyForImportExport(): string
    {
        $instance = new static;
        if (property_exists($instance, 'omni_porter_config') && isset($instance->omni_porter_config['unique_key'])) {
            return (string) $instance->omni_porter_config['unique_key'];
        }

        return 'id';
    }

    /**
     * Definitions for foreign-key relations that OmniPorter should resolve
     * during import (e.g. convert a department *name* to a `department_id`).
     *
     * @return array<string, class-string>
     */
    public static function getListOfRelationDetails(): array
    {
        $instance = new static;
        if (property_exists($instance, 'omni_porter_config') && isset($instance->omni_porter_config['relations'])) {
            return (array) $instance->omni_porter_config['relations'];
        }

        return [];
    }

    /**
     * Map operation names to FormRequest / Validator classes used for
     * row-level validation before persistence.
     *
     * Supported keys: `'create'`, `'update'`
     *
     * @return array<string, class-string>
     */
    public static function getImportValidators(): array
    {
        $instance = new static;
        if (property_exists($instance, 'omni_porter_config') && isset($instance->omni_porter_config['validation'])) {
            $validation = $instance->omni_porter_config['validation'];
            
            return [
                'create' => $validation,
                'update' => $validation,
            ];
        }

        return [];
    }

    /**
     * Hook: Runs immediately after the model is saved during the import process.
     *
     * This method allows the model to trigger side effects—such as dispatching events,
     * sending notifications, or creating audit logs—once the record has been successfully
     * persisted to the database.
     *
     * ---
     * ### Usage:
     * This is a "no-op" (empty) method by default. Override it in your model class
     * to define custom logic that must occur strictly after the save operation.
     *
     * ---
     * ### Example:
     * ```
     * public function afterImportSave(array $context): void
     * {
     *      if ($this->wasRecentlyCreated) {
     *          // Send a welcome email using data from the import context
     *          Mail::to($this->email)->queue(new WelcomeEmail($context['notifiable_email']));
     *      }
     *
     *      Log::info("Imported record {$this->id} in batch {$context['batch_id']}");
     * }
     * ```
     * ---
     * @param array<string, mixed> $context An associative array of contextual import data.
     * Example: ```['notifiable_email' => 'user@example.com', 'source' => 'excel', 'batch_id' => '...']```
     * @return void
     */
     public function afterImportSave(array $context): void {}
}
